name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm install
      - name: Install pkg
        run: npm install -g pkg

      - name: Bundle
        run: npx pkg server.js --targets node18-win-x64 --output gyroclopter.exe

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-version-file: 'true'
          skip-commit: 'true'

      - name: Create Release
        if: steps.changelog.outputs.skipped == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          files: gyroclopter.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
